# Generated by Django 3.2.4 on 2021-06-29 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dictation',
            name='content_id',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='groupofwords',
            name='content_id',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='idiom',
            name='content_id',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='question',
            name='content_id',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='rule',
            name='content_id',
            field=models.SmallIntegerField(default=0),
        ),
    ]
