# Generated by Django 3.1.4 on 2021-07-04 12:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20210701_2234'),
    ]

    operations = [
        migrations.AddField(
            model_name='idiom',
            name='lesson',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='idioms', to='app.lesson'),
        ),
        migrations.AlterField(
            model_name='dictation',
            name='lesson',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dictations', to='app.lesson'),
        ),
        migrations.AlterField(
            model_name='groupofwords',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups_of_words', to='app.lesson'),
        ),
        migrations.AlterField(
            model_name='rule',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='app.lesson'),
        ),
    ]
