# Generated by Django 3.1.4 on 2021-07-04 12:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20210704_1513'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupofwords',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups_of_words_set', to='app.lesson'),
        ),
        migrations.AlterField(
            model_name='question',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions_set', to='app.lesson'),
        ),
        migrations.AlterField(
            model_name='rule',
            name='index_number',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
    ]
