# Generated by Django 3.1.4 on 2021-07-04 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20210704_2308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idiom',
            name='example_text',
            field=models.CharField(max_length=120),
        ),
    ]
