# Generated by Django 3.1.4 on 2021-07-05 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20210704_2309'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='audio',
            field=models.FileField(null=True, upload_to='lessons_audio/'),
        ),
    ]
